output: output_recog
log_freq: 100 
image_writer_freq: 100 

data:
  batch_size: 64
  num_workers: 16
  image_folder: /mnt/data/faces/glint360k
  megaface_data_root: /mnt/data/megaface_clean
  megaface_face_folders: faces,facescrub_images,megaface_images
  sample_rate: 1.0

model:
  network: vit_s
  fp16: True 
  input_size: [112, 112]
  patch_size: 8
  freeze_patch_embed: True
  num_features: 512 
  ckpt: False 

train:
  num_epoch: 100 
  save_epoch: 10
  lock_epoch: 0
  warmup_epoch: 10
  lr: 5.e-4
  loss: arcface
  margin_list: [64.0, 0.4]
  optimizer: adamw 
  momentum: 0.9 
  weight_decay: 1.e-4
