output: output 
log_freq: 100 
image_writer_freq: 100 

data:
  batch_size: 64
  num_workers: 8
  resize: [112, 112]
  image_folder: /mnt/data/faces/ms1m
  sample_rate: 1.0
  megaface_data_root: /mnt/data/megaface_clean
  megaface_face_folders: faces,facescrub_images,megaface_images

model:
  network: swin 
  fp16: True 
  input_size: [112, 112]
  patch_size: 8
  num_features: 512 
  ckpt: False 

train:
  num_epoch: 22 
  save_epoch: 5
  lock_epoch: 0
  warmup_epoch: 2
  lr: 0.001 
  loss: arcface
  margin_list: [64.0, 0.4]
  optimizer: adamw 
  momentum: 0.9 
  weight_decay: 0.0001
