output: output_dino
log_freq: 100
image_writer_freq: 100

data:
  batch_size: 64
  num_workers: 16
  image_folder: /mnt/data/luperson/images
  megaface_data_root: /mnt/data/reid/Market1501
  megaface_face_folders: persons1,persons2
  global_crops_scale: [0.5, 1.0]
  global_crops_number: 2
  local_crops_scale: [0.05, 0.5]
  local_crops_number: 8
  mask_ratio: 0.5
  mask_ratio_var: 0
  mask_shape: block 
  mask_start_epoch: 0
  make_square: False
  rotate_degree: 0

model:
  network: vit_s 
  fp16: True 
  input_size: [384, 128]
  patch_size: 16 
  num_features: 512 
  out_dim: 65536 
  patch_out_dim: 8192 
  ckpt: False 

train:
  epochs: 100
  save_epoch: 10
  warmup_epochs: 10
  lock_last_layer: 1
  optimizer: adamw
  lr: 5.e-4
  lr_end: 1.e-6
  weight_decay: 0.04
  weight_decay_end: 0.4
  momentum_teacher: 0.996
  warmup_teacher_temp_epochs: 30
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  student_temp: 0.1
  center_momentum: 0.9
  lambda1: 1.0
  lambda2: 1.0
