output: output_recog
log_freq: 100 
image_writer_freq: 100 

data:
  batch_size: 32
  num_workers: 16
  image_folder: /mnt/data/faces/ms1m
  megaface_data_root: /mnt/data/megaface_clean
  megaface_face_folders: faces,facescrub_images,megaface_images

model:
  network: vit_s
  fp16: True 
  input_size: [112, 112]
  patch_size: 8
  freeze_patch_embed: True
  num_features: 512 
  ckpt: False 

train:
  epochs: 100 
  save_epoch: 10
  lock_epochs: 0
  warmup_epochs: 10
  lr: 1.e-3
  lr_end: 1.e-6
  gamma: 256 
  m: 0.25 
  sample_rate: 0.25
  optimizer: adamw 
  momentum: 0.9 
  weight_decay: 1.e-4
